Repository Nopm/Beat-Station, pull requests merged in 2019-09, with the labels that each got.

#47 adds looc
  beatstation.dme
  beatstation/code/modules/client/verbs/looc.dm
Labels: Feature

#51 Looc patch
  beatstation/code/modules/client/verbs/looc.dm
Labels: Fix, Tweak

#52 Looc syntax
  beatstation/code/modules/client/verbs/looc.dm
Labels: Administration

#54 Ebow new
  beatstation.dme
  beatstation/code/modules/projectiles/guns/energy/special.dm
  beatstation/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#61 Stone Mask!
  beatstation.dme
  beatstation/code/modules/clothing/masks/stonemask.dm
  beatstation/icons/mob/mask.dmi
  beatstation/icons/obj/clothing/masks.dmi
Labels: Feature

#62 Ports mining suits and suit vouchers from Citadel Station
  beatstation/code/modules/jobs/job_types/shaft_miner.dm
  beatstation/code/modules/mining/equipment/explorer_gear.dm
  beatstation/code/modules/mining/machine_vending.dm
  beatstation/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  beatstation/icons/mob/head.dmi
  beatstation/icons/mob/inhands/weapons/guns_lefthand.dmi
  beatstation/icons/mob/inhands/weapons/guns_righthand.dmi
  beatstation/icons/mob/mask.dmi
  beatstation/icons/mob/suit.dmi
  beatstation/icons/obj/clothing/hats.dmi
  beatstation/icons/obj/clothing/masks.dmi
  beatstation/icons/obj/clothing/suits.dmi
  beatstation/icons/obj/guns/energy.dmi
Labels: Feature

#72 rebuilds tgui
  tgui/assets/tgui.css
  tgui/assets/tgui.js
Labels: UI

#79 Adds a "botanical voucher"
  beatstation.dme
  beatstation/code/game/objects/items/miscellaneous.dm
  beatstation/code/modules/jobs/job_types/botanist.dm
  beatstation/code/modules/mining/equipment/explorer_gear.dm
Labels: Feature
