Repository Nopm/Beat-Station, pull requests merged in 2019-10, with the labels that each got.

#84 H.E.C.K. Suit Buff + New Clothes
  beatstation.dme
  beatstation/code/modules/clothing/head/head.dm
  beatstation/code/modules/clothing/suits/suits.dm
  beatstation/code/modules/clothing/under/under.dm
  beatstation/code/modules/mining/equipment/explorer_gear.dm
  beatstation/code/modules/vending/clothesmate.dm
  beatstation/icons/mob/head.dmi
  beatstation/icons/mob/suit.dmi
  beatstation/icons/mob/uniform.dmi
Labels: Balance/Rebalance, Feature

#91 MedMaga
  beatstation.dme
  beatstation/code/datums/martial/krav_medical.dm
  beatstation/code/modules/jobs/job_types/chemist.dm
  beatstation/code/modules/jobs/job_types/chief_medical_officer.dm
  beatstation/code/modules/jobs/job_types/geneticist.dm
  beatstation/code/modules/jobs/job_types/medical_doctor.dm
  beatstation/code/modules/jobs/job_types/virologist.dm
Labels: Feature, Tweak

#105 Fixes Blood Rites
  beatstation.dme
  beatstation/code/modules/antagonists/cult/blood_magic.dm
Labels: Fix

#106 tweaks the stone mask and adds new sprite
  beatstation/code/modules/clothing/masks/stonemask.dm
  beatstation/icons/obj/clothing/masks.dmi
Labels: Sprites, Tweak

#114 tweaks dynamic rulesets for our server
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Feature, Removal, Tweak

#121 Ports Shrine Maiden's Outfit from /tg/
  beatstation.dme
  beatstation/code/game/objects/items/holy_weapons.dm
  beatstation/code/modules/clothing/head/jobs.dm
  beatstation/code/modules/clothing/suits/chaplainsuits.dm
  beatstation/code/modules/vending/wardrobes.dm
  beatstation/icons/mob/inhands/weapons/staves_lefthand.dmi
  beatstation/icons/mob/inhands/weapons/staves_righthand.dmi
  beatstation/icons/mob/large-worn-icons/64x64/head.dmi
  beatstation/icons/mob/suit.dmi
  beatstation/icons/obj/clothing/hats.dmi
  beatstation/icons/obj/clothing/suits.dmi
  beatstation/icons/obj/items_and_weapons.dmi
Labels: Feature

#122 Adds back adrenaline burst
  beatstation.dme
  beatstation/code/modules/research/designs/nanite_designs.dm
  beatstation/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#139 Fixes Ignore verb
  beatstation.dme
  beatstation/code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/ooc.dm
Labels: Fix

#144 Adds Beat!Box
  _maps/_basemaphippie.dm
  _maps/beat!box.dm
  _maps/beat!box.json
  _maps/map_files/Beat!Box/Beat!Box.dmm
  config/maps.txt
Labels: Config Update, Feature, Map Edit

#145 Fixes cargo tech access
  beatstation/code/modules/jobs/job_types/cargo_technician.dm
Labels: Fix

#148 Adds stock market back
  _maps/map_files/Beat!Box/Beat!Box.dmm
  beatstation.dme
  beatstation/code/game/objects/items/circuitboards/computer_circuitboards.dm
  beatstation/code/modules/research/designs/comp_board_designs.dm
  beatstation/code/modules/research/techweb/all_nodes.dm
  beatstation/code/modules/stock_market/articles.dm
  beatstation/code/modules/stock_market/computer.dm
  beatstation/code/modules/stock_market/events.dm
  beatstation/code/modules/stock_market/industries.dm
  beatstation/code/modules/stock_market/logs.dm
  beatstation/code/modules/stock_market/stockmarket.dm
  beatstation/code/modules/stock_market/stocks.dm
Labels: Feature, Map Edit

#149 Adds beebox to hydro
  _maps/map_files/Beat!Box/Beat!Box.dmm
  beatstation.dme
  beatstation/code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
Labels: Map Edit
