Repository Nopm/Beat-Station, pull requests merged in 2020-04, with the labels that each got.

#583 Actually plays the snap emote...
  hippiestation/code/modules/guardian/abilities/major/explosive.dm
Labels: Fix

#594 Improves the old chapel from Donut Station
  _maps/map_files/Beat!Donut/Beat!Donut.dmm
Labels: Feature, Map Edit, Tweak

#593 The Opaopapanerd Statue
  beatstation/icons/obj/statueopao.dmi
  beatstation/obj/structures/statues.dm
  beatstation/sound/misc/opao.ogg
Labels: Feature

#603 Removes no admins online from irc messages
  code/modules/client/client_procs.dm
Labels: Removal

#630 fix sounds
  code/__DEFINES/footsteps.dm
  hippiestation/sound/machines/airlock.ogg
  sound/effects/footstep/floor1.ogg
  sound/effects/footstep/floor2.ogg
  sound/effects/footstep/floor3.ogg
  sound/effects/footstep/floor4.ogg
  sound/effects/footstep/floor5.ogg
  sound/effects/footstep/plating1.ogg
  sound/effects/footstep/plating2.ogg
  sound/effects/footstep/plating3.ogg
  sound/effects/footstep/plating4.ogg
  sound/effects/footstep/plating5.ogg
  sound/machines/airlock.ogg
Labels: Fix, Sound
