Repository Nopm/Beat-Station, pull requests merged in 2020-03, with the labels that each got.

#552 uncurses master branch
  beatstation/code/game/objects/items/devices/polycircuit.dm
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/datums/explosion.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/power/solar.dm
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: UI

#554 Makes damage to the test dummy visible
  beatstation.dme
  beatstation/code/game/objects/effects/temporary_visuals/damage_number.dm
  beatstation/code/game/objects/items/shooting_range.dm
  code/game/objects/items/shooting_range.dm
Labels: Feature

#557 updates changelog & tgui actions
  .github/workflows/autobuild_tgui.yml
  .github/workflows/autochangelog_compile.yml
Labels: GitHub

#567 Added a new ruin called Old Guarana Station.
  _maps/RandomRuins/SpaceRuins/oldguaranastation.dmm
  beatstation/code/datums/ruins/space.dm
Labels: Feature, Map Edit

#573 Changes beanbag slug sound effect
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Tweak

#577 Revert "Changes beanbag slug sound effect"
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Revert

#578 Makes explosive guardians cooler
  hippiestation/code/modules/guardian/abilities/major/explosive.dm
Labels: Tweak
