Repository Nopm/Beat-Station, pull requests merged in 2020-01, with the labels that each got.

#367 Fixes ghost stone being able to revive thanos
  hippiestation/code/modules/gauntlet/ghost.dm
Labels: Fix

#368 makes power transmission circuit able to recharge guns again
  hippiestation/code/modules/integrated_electronics/subtypes/power.dm
Labels: Tweak

#375 Fixes invisimin appearing in data huds
  code/modules/admin/admin_verbs.dm
Labels: Fix

#376 Da icon update
  beatstation.dme
  hippiestation/code/game/machinery/announcement_system.dm
  hippiestation/code/game/machinery/autolathe.dm
  hippiestation/code/game/machinery/cell_charger.dm
  hippiestation/code/game/machinery/computer/_computer.dm
  hippiestation/code/game/machinery/doppler_array.dm
  hippiestation/code/game/machinery/pipe/pipe_dispenser.dm
  hippiestation/code/game/machinery/recharger.dm
  hippiestation/code/game/machinery/telecomms/telecommunications.dm
  hippiestation/code/game/machinery/washing_machine.dm
  hippiestation/code/game/mecha/mech_fabricator.dm
  hippiestation/code/game/objects/items/apc_frame.dm
  hippiestation/code/game/objects/items/storage/boxes.dm
  hippiestation/code/game/objects/items/storage/toolbox.dm
  hippiestation/code/game/objects/structures/crates_lockers/closets.dm
  hippiestation/code/game/objects/structures/crates_lockers/crates.dm
  hippiestation/code/game/objects/structures/crematorium.dm
  hippiestation/code/game/objects/structures/tables_racks.dm
  hippiestation/code/game/objects/structures/tank_dispenser.dm
  hippiestation/code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  hippiestation/code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  hippiestation/code/modules/hydroponics/biogenerator.dm
  hippiestation/code/modules/hydroponics/seed_extractor.dm
  hippiestation/code/modules/library/lib_machines.dm
  hippiestation/code/modules/mining/machine_processing.dm
  hippiestation/code/modules/mining/machine_stacking.dm
  hippiestation/code/modules/mining/machine_unloading.dm
  hippiestation/code/modules/modular_computers/NTNet/NTNet_relay.dm.dm
  hippiestation/code/modules/modular_computers/computers/item/laptop.dm
  hippiestation/code/modules/modular_computers/computers/machinery/modular_console.dm
  hippiestation/code/modules/paperwork/filingcabinet.dm
  hippiestation/code/modules/paperwork/paperbin.dm
  hippiestation/code/modules/paperwork/pen.dm
  hippiestation/code/modules/paperwork/photocopier.dm
  hippiestation/code/modules/power/apc.dm
  hippiestation/code/modules/power/solar.dm
  hippiestation/code/modules/reagents/chemistry/machinery/chem_heater.dm
  hippiestation/code/modules/reagents/machinery.dm
  hippiestation/code/modules/reagents/reagent_dispenser.dm
  hippiestation/code/modules/research/message_server.dm
  hippiestation/code/modules/research/rdmachines.dm
  hippiestation/code/modules/research/stock_parts.dm
  hippiestation/code/modules/stock_market/computer.dm
  hippiestation/code/modules/vending/_vending.dm
Labels: Sprites

#379 Map fixes in kilo and beat!box
  _maps/map_files/Beat!Box/Beat!Box.dmm
  _maps/map_files/Beat!Kilo/Beat!Kilo.dmm
Labels: Map Edit

#381 unfucks AI vox announces
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/events/blob.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/ion_storm.dm
  code/modules/events/meateor_wave.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/wormholes.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/shuttle/emergency.dm
  code/modules/station_goals/station_goal.dm
  hippiestation/code/controllers/subsystem/communications.dm
  hippiestation/code/controllers/subsystem/shuttle.dm
  hippiestation/code/modules/shuttle/emergency.dm
Labels: Removal, Sound

#384 UI for the normal protolathe and the circuit imprinter
  beatstation.dme
  beatstation/code/modules/research/machinery/circuit_imprinter.dm
  beatstation/code/modules/research/machinery/protolathe.dm
  code/game/machinery/_machinery.dm
Labels: Tweak

#388 Revert "[MIRROR] Adds extremely trippy sound effects to grape blast [READY]"
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Revert

#387 Fixes books
  beatstation.dme
  beatstation/code/game/objects/items/manuals.dm
Labels: Fix

#389 Adds a new space ruin
  _maps/RandomRuins/SpaceRuins/viladochavesabandonada.dmm
  beatstation.dme
  beatstation/code/datums/ruins/space.dm
  config/spaceruinblacklist.txt
Labels: Config Update, Feature, Map Edit

#392 Tweaks vila do chaves space ruin
  _maps/RandomRuins/SpaceRuins/viladochavesabandonada.dmm
Labels: Feature, Fix, Map Edit

#393 Tweaks Vila do Chaves space ruin
  _maps/RandomRuins/SpaceRuins/viladochavesabandonada.dmm
Labels: Feature, Map Edit

#406 monkey alert
  beatstation/sound/misc/monkeyalert.ogg
  code/__HELPERS/priority_announce.dm
  hippiestation/code/__HELPERS/priority_announce.dm
Labels: Sound

#417 Adds power gloves
  beatstation.dme
  beatstation/code/modules/clothing/gloves/color.dm
  beatstation/code/modules/uplink/uplink_items.dm
  hippiestation/code/modules/mob/living/carbon/carbon_defense.dm
Labels: Feature

#420 Increases the cost of the energy butterfly knife
  beatstation/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#422 Some map fixes
  _maps/RandomRuins/StationRuins/BeatBox/bar_casino.dmm
  _maps/RandomRuins/StationRuins/BeatBox/bar_purple.dmm
  _maps/RandomRuins/StationRuins/BeatBox/xenobridge_space.dmm
  _maps/map_files/Beat!Box/Beat!Box.dmm
Labels: Fix, Map Edit

#431 Makes the wizard academy defender spawns in the academy
  beatstation.dme
  beatstation/code/modules/antagonists/wizard/wizard.dm
Labels: Fix

#430 Ports B.E.P.I.S
  beatstation.dme
  beatstation/code/game/objects/items/RCD.dm
  beatstation/code/game/objects/items/airlock_painter.dm
  beatstation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  beatstation/code/game/objects/items/devices/polycircuit.dm
  beatstation/code/game/objects/items/stacks/cash.dm
  beatstation/code/game/objects/items/stacks/rods.dm
  beatstation/code/game/objects/items/stunbaton.dm
  beatstation/code/game/objects/structures/lattice.dm
  beatstation/code/game/turfs/simulated/lava.dm
  beatstation/code/modules/clothing/gloves/color.dm
  beatstation/code/modules/clothing/head/hardhat.dm
  beatstation/code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  beatstation/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  beatstation/code/modules/paperwork/pen.dm
  beatstation/code/modules/paperwork/photocopier.dm
  beatstation/code/modules/projectiles/pins.dm
  beatstation/code/modules/research/bepis.dm
  beatstation/code/modules/research/designs/machine_designs.dm
  beatstation/code/modules/research/designs/misc_designs.dm
  beatstation/code/modules/research/designs/tool_designs.dm
  beatstation/code/modules/research/designs/weapon_designs.dm
  beatstation/code/modules/research/research_disk.dm
  beatstation/code/modules/research/techweb/_techweb.dm
  beatstation/code/modules/research/techweb/_techweb_node.dm
  beatstation/code/modules/research/techweb/all_nodes.dm
  beatstation/icons/mob/animal.dmi
  beatstation/icons/mob/head.dmi
  beatstation/icons/mob/inhands/equipment/security_lefthand.dmi
  beatstation/icons/mob/inhands/equipment/security_righthand.dmi
  beatstation/icons/obj/bureaucracy.dmi
  beatstation/icons/obj/clothing/hats.dmi
  beatstation/icons/obj/device.dmi
  beatstation/icons/obj/economy.dmi
  beatstation/icons/obj/items_and_weapons.dmi
  beatstation/icons/obj/machines/bepis.dmi
  beatstation/icons/obj/module.dmi
  beatstation/icons/obj/objects.dmi
  beatstation/icons/obj/stack_objects.dmi
  code/__DEFINES/~hippie_defines/traits.dm
  code/controllers/subsystem/research.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/lava.dm
  tgui-next/packages/tgui/interfaces/Bepis.js
  tgui-next/packages/tgui/interfaces/DecalPainter.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Feature, Fix, Tweak, UI

#435 Adds Circuitry Lab
  _maps/RandomRuins/StationRuins/BeatBox/sci_circuitry.dmm
  _maps/RandomRuins/StationRuins/BeatBox/sci_telescience.dmm
  _maps/map_files/Beat!Box/Beat!Box.dmm
  beatstation/code/datums/ruins/station.dm
  beatstation/code/game/area/Space_Station_13_areas.dm
  beatstation/code/game/objects/effects/landmarks.dm
  beatstation/icons/rooms/maint_xenobio.dmi
Labels: Feature, Map Edit

#439 Replaces stungun with the telescopic baton
  hippiestation/code/modules/jobs/job_types/captain.dm
  hippiestation/code/modules/jobs/job_types/engineering.dm
  hippiestation/code/modules/jobs/job_types/medical.dm
  hippiestation/code/modules/jobs/job_types/science.dm
Labels: Tweak

#442 Shuttles now throw everything that is unbuckled
  code/modules/shuttle/shuttle.dm
Labels: Tweak

#451 Atmos remap
  _maps/RandomRuins/StationRuins/BeatBox/maint_detective.dmm
  _maps/RandomRuins/StationRuins/BeatBox/maint_rpg.dmm
  _maps/RandomRuins/StationRuins/BeatBox/xenobridge_default.dmm
  _maps/RandomRuins/StationRuins/BeatBox/xenobridge_space.dmm
  _maps/map_files/Beat!Box/Beat!Box.dmm
  beatstation/code/datums/ruins/station.dm
  beatstation/code/game/area/Space_Station_13_areas.dm
  beatstation/code/game/objects/effects/landmarks.dm
  beatstation/icons/rooms/maint_xenobio.dmi
Labels: Feature, Map Edit, Tweak

#452 Revert "Revert "[MIRROR] Adds extremely trippy sound effects to grape blast [READY]""
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Revert

#453 Xenobio revamp
  _maps/RandomRuins/StationRuins/BeatBox/bar_spacious.dmm
  _maps/RandomRuins/StationRuins/BeatBox/sci_circuitry.dmm
  _maps/RandomRuins/StationRuins/BeatBox/sci_telescience.dmm
  _maps/RandomRuins/StationRuins/BeatBox/xenobridge_default.dmm
  _maps/RandomRuins/StationRuins/BeatBox/xenobridge_space.dmm
  _maps/map_files/Beat!Box/Beat!Box.dmm
  beatstation/icons/rooms/maint_xenobio.dmi
Labels: Feature, Map Edit
